### ISSUE TITLE
Support Ctrl/Capslock swap

### ISSUE THREAD

**Issue by zw963** [kawao/x-set-keys#1]
Hello, I use a [forked](https://github.com/zw963/linux_key_rebinding) version [rbindkeys](http://github.com/kui/rbindkeys) to archive same effect to rebinding key globally for X.

But, that gem is not active maintained, and the dependency gem: [active_window_x](https://github.com/kui/active_window_x) is not worked for newer version linux distro.

e.g. Ubuntu 14.4 work, but > Ubuntu 16.04 not worked
OpenSUSE 42.1 worked, but > 42.3 not work.

So, I have to change a alternative as instead, But this missing two feature:

1. Map Left Ctrl to Capslock, and map Capslock to Right Alt
2.  Map same hostkey to different keybindings according app class.
  
Those two feature all work well with older linux distro and rbindkeys,
 e.g. Slackware 14.2
But for newer distro, [active_window_x](https://github.com/kui/active_window_x) c extension
is broken, make rbindkeys not work.

I hope maybe have change to add above features into x-set-keys, or, help fix active_window_x
gem ? thanks.

BTW: rbindkeys is come from jp too. thanks so many wonderful tools.

**Comment by zw963** [comment]
I think add a --include arg is a good idea. e.g. I want to use a suite keybindings only for current terminal,
so, i can run a seperate `x-set-keys` command, only take effect when i input in terminal.

following is a example:
```sh
x-set-key --include 'xfce4-terminal' --include 'Konsole' some/config/for/terminal.conf
```

**Comment by kawao** [comment]
> I think add a --include arg is a good idea. e.g. I want to use a suite keybindings only for current terminal,
so, i can run a seperate x-set-keys command, only take effect when i input in terminal.

You can only run one x-set-keys at a time, because x-set-keys grab keyboard device.
So, it is not easy to realize your wishes.

Thank you.

**Comment by zw963** [comment]
> You can only run one x-set-keys at a time, because x-set-keys grab keyboard device.
> So, it is not easy to realize your wishes.

Thanks for reply.

Is there any plan to support `Ctrl/Capslock swap` ?

**Comment by kawao** [comment]
> Is there any plan to support Ctrl/Capslock swap ?

For now, I do not have that plan, sorry.

If you are using Ubuntu or Debian, you can swap Ctrl and CapsLock by editing /etc/default/keyboard.
```
XKBOPTIONS="ctrl:swapcaps"
```

In addition to the above, there are some tools to swap Ctrl and CapsLock. In this case, please execute x-set-keys after key swapping.

Is the above useless?

Thank you.

**Comment by zw963** [comment]
> If you are using Ubuntu or Debian, you can swap Ctrl and CapsLock by editing /etc/default/keyboard.
> 
> XKBOPTIONS="ctrl:swapcaps"

Thanks, i still not use this, current no Ubuntu to test.

> In addition to the above, there are some tools to swap Ctrl and CapsLock. In this case, please execute x-set-keys after key swapping.

I done this use `Xmodmap`, it worked, but, I must run `xmodmap ~/.Xmodmap &>/dev/null` after x-set-keys

**Comment by zw963** [comment]
Thanks you.
