### ISSUE TITLE
Rebinding emacs C-< to S-Home and C-> to S-End not worked.

### ISSUE THREAD

**Issue by zw963** [kawao/x-set-keys#4]
Hi, i tried to following config, all not work

```sh
A-S-comma :: S-Home
A-S-period :: S-End
```

```sh
A-less :: S-Home
A-greater :: S-End
```

thanks

**Comment by zw963** [comment]
Following is X keybinding guide.

https://www.safaribooksonline.com/library/view/xlib-reference-manual/9780937175262/16_appendix-h.html

![p628-001.jpg](http://zw963.github.io/images/157832163727871.jpg)

Maybe i search wrong document ?

**Comment by kawao** [comment]
In my environment, the following worked.

```
A-S-comma :: S-Home
A-S-period :: S-End
```

What is your keyboard model and keyboard layout?
And if you have changed the keymap with xmodmap etc, could you please tell me about its settings? (especially about modifier keys, alt etc.)

Thanks.

**Comment by zw963** [comment]
@kawao , It worked, sorry for confusing ... i add test console into exclude list ....

**Comment by zw963** [comment]
My xmodmap settings is working for years, though, get some error message when run.

```
remove lock = Caps_Lock
add control = Caps_Lock
keysym Caps_Lock = Control_L
remove mod1 = Alt_R
add lock = Alt_R
keysym Alt_R = Caps_Lock
```

Please give some advise if you find some wrong or unnecessory config.

Thanks
