### ISSUE TITLE
x-set-keys --exclude-focus-class not working after kill x-set-keys process and rerun

### ISSUE THREAD

**Issue by zw963** [kawao/x-set-keys#5]
I have a new laptop (Thinkpad T480S), and run in a new linux distro (Deepin 15.5), When use with x-set-keys, after suspend and awake again, x-set-keys not working. (maybe this is another issue need be fixed)

So, i have to kill x-set-keys and rerun it, it worked, but the `-e Emacs` is not working, when i switch to emacs, i can feel clearly it controlled by x-set-keys,  as issue #3, when I KEEPING press Ctrl+p in emacs,
if `-e Emacs` take effect, I can move cursor up to prevoius line very quickly without any delay time,  but for now, it wait about 0.3 seconds at first, and then worked as usual, so, i know exclude option is not working.

Thanks

**Comment by kawao** [comment]
Was it normal before suspend?

Was Emacs normal after awake and before rerun x-set-keys?

During the occurrence of this trouble, can you please run `xprop WM_CLASS` in a terminal and click the Emacs window and post the terminal output line? Just in case.

Thanks.

**Comment by zw963** [comment]
>> Was it normal before suspend?

Yes

>> Was Emacs normal after awake and before rerun x-set-keys?

No, all keybinding is missing

**Comment by zw963** [comment]
> During the occurrence of this trouble, can you please run xprop WM_CLASS in a terminal and click the Emacs window and post the terminal output line? Just in case.

Following is output when i kill and rerun x-set-keys .

╰─ $ xprop WM_CLASS
WM_CLASS(STRING) = "emacs", "Emacs"

**Comment by zw963** [comment]
Following is my command:

```sh
$: x-set-keys -d /dev/input/event19 -e Emacs -e Konsole -e konsole -e Deepin-terminal /home/zw963/Dropbox/linux/utils/x-set-keys/bin/../emacslike.conf
```

**Comment by zw963** [comment]
And, I use `x-set-keys` with `Xmodmap` and `xbindkeys`.

it run as follow order:

```sh
daemon xbindkeys
daemon x-set-keys
xmodmap ~/.Xmodmap &>/dev/null
```

I have to invoke twice to make `Capslock => Ctrl` work.

**Comment by zw963** [comment]
hi, @kawao , seem like this issue is same with #7 i think.

--exclude option seem like worked, but, after restart x-set-keys, 
it revert all keyboard config,  include repeating settings,
cause delay issue,  after run `xset r rate 200 20` command,  
i can work around this issue.

**Comment by zw963** [comment]
After compare `xset q` output info, i found some clue..

When my linux start, my repeat settings is:

```sh
auto repeat delay:  360    repeat rate:  20
```

But, after run x-set-keys, it change this value to:

```sh
auto repeat delay:  660    repeat rate:  25
```

I think some code in x-set-keys, add __300 ms to auto repeat delay__  (660 - 360)

```
Thanks

**Comment by zw963** [comment]
It change report rate from 20 to 25  too.

**Comment by zw963** [comment]
does i explain clear enough?  @kawao , thanks

**Comment by kawao** [comment]
I'm sorry for the delay. Please wait a few more days.

**Comment by zw963** [comment]
@kawao , I see some logs maybe help for seek

when i computer into suspend mode, some logs is appear:

```sh
** (x-set-keys:7958): CRITICAL **: Hang up keyboard device : Resource temporarily unavailable
** Message: Initiating restart

** (x-set-keys:7958): CRITICAL **: Failed to ungrab keyboard device : No such device
** Message: Restarting

** (x-set-keys:7958): CRITICAL **: Failed to open /dev/input/event6 : No such file or directory
** Message: Initiating shutdown
** Message: Exiting
```

**Comment by kawao** [comment]
Thanks for the report.
If you omit the -d option (remove '-d /dev/input/event6' from the command line), how do the behavior and the logs change?

**Comment by zw963** [comment]
@kawao 


> If you omit the -d option (remove '-d /dev/input/event6' from the command line), how do the behavior and the logs change?

Hi, i could not omit that option, because, I use a usb keyboard, i must make x-set-key binding to this usb keyboard, what i do is use bash to find the correct keyboard:

```sh
keyboard=$(find /dev/input/by-id/ -name '*USB_Keyboard-event-kbd' |head -n1)
if [ "$keyboard" ]; then
    keyboard=$(readlink -e $keyboard)
else
    unset keyboard
fi
x-set-keys -d $keyboard -e emacs -e Konsole emacslike.conf
```

**Comment by zw963** [comment]
Oh, i think the reason keyboard not work maybe caused by this ...

so i have to rerun x-set-keys if switch keyboard ...

**Comment by kawao** [comment]
```sh
keyboard=$(find /dev/input/by-id/ -name '*USB_Keyboard-event-kbd' |head -n1)
if [ "$keyboard" ]; then
    keyboard=$(readlink -e $keyboard)
else
    unset keyboard
fi
```

I do not think readlink is necessary. It is better to remain as a symbolic link for x-set-keys.

For your other issues, I am currently correcting the program.
Please wait a more few days.

Thanks.

**Comment by zw963** [comment]
> I do not think readlink is necessary. It is better to remain as a symbolic link for x-set-keys.

Hi, this hack is worked, for now, i don't have to rerun `x-set-keys` if i am not change keyboad.

I have a good advise, if input device which grab by x-set-keys is missing , we should broken 
x-set-keys (it not worked, right?), and after i open a new terminal, i will rerun `x-set-keys` if not
found this process name.

But, this issue is still exist, --exclude-focus-class not work after rerun.

**Comment by zw963** [comment]
> I have a good advise, if input device which grab by x-set-keys is missing , we should broken
> x-set-keys (it not worked, right?), and after i open a new terminal, i will rerun x-set-keys if not
> found this process name.

It seem like this feature is working, sorry


> But, this issue is still exist, --exclude-focus-class not work after rerun.

I think `exclude-fodus-class` is worked!  the real issue is when rerun x-set-keys, it change
xset repeat delay globally, give me a illusion about it not work.

so, the really problem is #3, so i close this. thanks
